apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # joancemac@gmail.com
  PG_USER_EMAIL: am9hbmNlbWFjQGdtYWlsLmNvbQ==
  # EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=