version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - userDB=joancema
    env_file:
      - ./env/mongo.env
    ports:
      - 27017:27017
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: backDockerfile
    ports:
      - 2000:2000
    volumes:
      - ./backend:/app
      - /app/node_modules   
    env_file:
      - ./env/backend.env   
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frotend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data: 
